apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vival

resources:
  - ../../base
  - secrets.yaml

images:
  - name: ghcr.io/isaksamsten/voice-grader/web
    newTag: main
  - name: ghcr.io/isaksamsten/voice-grader/worker
    newTag: main
  - name: ghcr.io/isaksamsten/voice-grader/migrate
    newTag: main
  - name: ghcr.io/isaksamsten/voice-grader/agent
    newTag: main
