apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prog2review

resources:
  - ../../base
  - secrets.yaml

images:
  - name: ghcr.io/edwinexd/dsv-prog2review
    newTag: latest
  - name: ghcr.io/edwinexd/dsv-prog2review-compiler
    newTag: latest
