apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vival

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - id-generator.yaml
  - app.yaml
  - worker.yaml
  - backup.yaml
