apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prog2review

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - id-generator.yaml
  - java-compiler.yaml
  - app.yaml
